import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReceiptPDF = (receipt: any) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(16, 185, 129); // brand-500
    doc.text("RECEIPT", 105, 20, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Receipt #: ${receipt.receipt_number}`, 140, 40);
    doc.text(`Date: ${new Date(receipt.issued_date).toLocaleDateString()}`, 140, 45);
    doc.text(`Status: ${receipt.status.toUpperCase()}`, 140, 50);

    // Client Info
    doc.text("Bill To:", 20, 40);
    doc.setFont("helvetica", "bold");
    doc.text(receipt.client_name, 20, 45);
    doc.setFont("helvetica", "normal");
    if (receipt.client_email) doc.text(receipt.client_email, 20, 50);

    // Items Table
    const tableColumn = ["Description", "Quantity", "Rate", "Amount"];
    const tableRows = receipt.items.map((item: any) => [
        item.description,
        item.quantity,
        `$${Number(item.rate).toFixed(2)}`,
        `$${Number(item.amount).toFixed(2)}`
    ]);

    autoTable(doc, {
        startY: 60,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [16, 185, 129] }, // brand-500
        styles: { fontSize: 10 },
    });

    // Totals
    const finalY = (doc as any).lastAutoTable.finalY + 10;

    doc.text(`Subtotal:`, 140, finalY);
    doc.text(`$${Number(receipt.subtotal).toFixed(2)}`, 180, finalY, { align: "right" });

    doc.text(`Tax:`, 140, finalY + 5);
    doc.text(`$${Number(receipt.tax).toFixed(2)}`, 180, finalY + 5, { align: "right" });

    doc.setFont("helvetica", "bold");
    doc.text(`Total:`, 140, finalY + 12);
    doc.text(`$${Number(receipt.total).toFixed(2)}`, 180, finalY + 12, { align: "right" });

    // Notes
    if (receipt.notes) {
        doc.setFont("helvetica", "normal");
        doc.text("Notes:", 20, finalY + 20);
        doc.setFontSize(9);
        doc.text(receipt.notes, 20, finalY + 25);
    }

    // Footer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Quickslip", 105, 280, { align: "center" });

    doc.save(`Receipt-${receipt.receipt_number}.pdf`);
};
