import { NextRequest, NextResponse } from 'next/server';
import { renderToBuffer } from '@react-pdf/renderer';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica' },
    header: { fontSize: 24, textAlign: 'center', color: '#10b981', marginBottom: 20, fontWeight: 'bold' },
    infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
    infoBlock: { flex: 1 },
    label: { fontSize: 9, color: '#666', marginBottom: 4 },
    value: { fontSize: 11, fontWeight: 'bold' },
    table: { marginTop: 20, marginBottom: 20 },
    tableHeader: { flexDirection: 'row', backgroundColor: '#10b981', padding: 8, color: 'white', fontWeight: 'bold' },
    tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', padding: 8 },
    col1: { width: '40%' },
    col2: { width: '20%', textAlign: 'center' },
    col3: { width: '20%', textAlign: 'right' },
    col4: { width: '20%', textAlign: 'right' },
    totalsSection: { marginTop: 20, alignItems: 'flex-end' },
    totalRow: { flexDirection: 'row', justifyContent: 'space-between', width: 200, marginBottom: 8 },
    totalLabel: { fontSize: 10 },
    totalValue: { fontSize: 10, textAlign: 'right' },
    grandTotal: { fontSize: 14, fontWeight: 'bold', borderTopWidth: 2, borderTopColor: '#000', paddingTop: 8 },
    notes: { marginTop: 30, padding: 10, backgroundColor: '#f9fafb', borderRadius: 4 },
    notesLabel: { fontSize: 10, fontWeight: 'bold', marginBottom: 4 },
    notesText: { fontSize: 9, color: '#666' },
    footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#999' },
});

const ReceiptDocument = ({ receipt }: { receipt: any }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <Text style={styles.header}>RECEIPT</Text>
            <View style={styles.infoRow}>
                <View style={styles.infoBlock}>
                    <Text style={styles.label}>Bill To:</Text>
                    <Text style={styles.value}>{receipt.client_name}</Text>
                    {receipt.client_email && <Text style={{ fontSize: 9, marginTop: 2 }}>{receipt.client_email}</Text>}
                </View>
                <View style={styles.infoBlock}>
                    <Text style={styles.label}>Receipt #:</Text>
                    <Text style={styles.value}>{receipt.receipt_number}</Text>
                    <Text style={[styles.label, { marginTop: 8 }]}>Date:</Text>
                    <Text style={styles.value}>{new Date(receipt.issued_date).toLocaleDateString()}</Text>
                    <Text style={[styles.label, { marginTop: 8 }]}>Status:</Text>
                    <Text style={styles.value}>{receipt.status.toUpperCase()}</Text>
                </View>
            </View>
            <View style={styles.table}>
                <View style={styles.tableHeader}>
                    <Text style={styles.col1}>Description</Text>
                    <Text style={styles.col2}>Qty</Text>
                    <Text style={styles.col3}>Rate</Text>
                    <Text style={styles.col4}>Amount</Text>
                </View>
                {receipt.items.map((item: any, index: number) => (
                    <View key={index} style={styles.tableRow}>
                        <Text style={styles.col1}>{item.description}</Text>
                        <Text style={styles.col2}>{item.quantity}</Text>
                        <Text style={styles.col3}>${Number(item.rate).toFixed(2)}</Text>
                        <Text style={styles.col4}>${Number(item.amount).toFixed(2)}</Text>
                    </View>
                ))}
            </View>
            <View style={styles.totalsSection}>
                <View style={styles.totalRow}>
                    <Text style={styles.totalLabel}>Subtotal:</Text>
                    <Text style={styles.totalValue}>${Number(receipt.subtotal).toFixed(2)}</Text>
                </View>
                <View style={styles.totalRow}>
                    <Text style={styles.totalLabel}>Tax:</Text>
                    <Text style={styles.totalValue}>${Number(receipt.tax).toFixed(2)}</Text>
                </View>
                <View style={[styles.totalRow, styles.grandTotal]}>
                    <Text style={styles.totalLabel}>Total:</Text>
                    <Text style={styles.totalValue}>${Number(receipt.total).toFixed(2)}</Text>
                </View>
            </View>
            {receipt.notes && (
                <View style={styles.notes}>
                    <Text style={styles.notesLabel}>Notes:</Text>
                    <Text style={styles.notesText}>{receipt.notes}</Text>
                </View>
            )}
            <Text style={styles.footer}>Generated by Quickslip</Text>
        </Page>
    </Document>
);

import { uploadFile } from '@/lib/s3';
import { createSupabaseServerClient } from '@/lib/supabase/server';

export async function POST(request: NextRequest) {
    try {
        const receipt = await request.json();
        const buffer = await renderToBuffer(<ReceiptDocument receipt={receipt} />);

        // Upload to S3
        const key = `quickslip/users/${receipt.user_id}/receipts/${receipt.id}.pdf`;
        await uploadFile(key, buffer, 'application/pdf');

        // Update database
        const supabase = await createSupabaseServerClient();
        await supabase
            .from('receipts')
            .update({ pdf_url: key })
            .eq('id', receipt.id);

        return NextResponse.json({ success: true, key });
    } catch (error) {
        console.error('PDF generation error:', error);
        return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 });
    }
}
